### ISSUE TITLE
Cannot install requirement for project!!

### ISSUE THREAD

**Issue by c0g4ih4l4n** [n4xh4ck5/CMSsc4n#2]
I have an error when install dependency for CMSsc4n.

> Invalid requirement: 'Module dependencies (installable via pip):'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/_internal/req/constructors.py", line 253, in install_req_from_line
    req = Requirement(req)
  File "/usr/share/python-wheels/packaging-18.0-py2.py3-none-any.whl/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8], e.msg
InvalidRequirement: Parse error at "u'dependen'": Expected stringEnd

I don't familiar with python. Sorry for this if it's a stupid question

**Comment by thiago0x00** [comment]
Coud you give more details?

**Comment by f8al** [comment]
remove the first line in requirements.txt.  its erroring because "'Module dependencies (installable via pip):" is not a valid package name when your reading the file with `pip install -r requirements.txt`
